// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMgBKONZDD5f0gaWn_67ZRMPQkvhxLQI',
    appId: '1:177992848215:web:222dca9cf4e206faaee412',
    messagingSenderId: '177992848215',
    projectId: 'orbit-app-85564',
    authDomain: 'orbit-app-85564.firebaseapp.com',
    storageBucket: 'orbit-app-85564.firebasestorage.app',
    measurementId: 'G-02WBTJM4YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQ4AsN7NUdMdluhLfuHzYPlK7qCqcuTA',
    appId: '1:177992848215:android:e0c2b27846e7298daee412',
    messagingSenderId: '177992848215',
    projectId: 'orbit-app-85564',
    storageBucket: 'orbit-app-85564.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdYnXLr3iY_Nc0IiLPkcrfpViGmKbzXnY',
    appId: '1:177992848215:ios:54a421885d423db2aee412',
    messagingSenderId: '177992848215',
    projectId: 'orbit-app-85564',
    storageBucket: 'orbit-app-85564.firebasestorage.app',
    iosBundleId: 'com.example.orbitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdYnXLr3iY_Nc0IiLPkcrfpViGmKbzXnY',
    appId: '1:177992848215:ios:54a421885d423db2aee412',
    messagingSenderId: '177992848215',
    projectId: 'orbit-app-85564',
    storageBucket: 'orbit-app-85564.firebasestorage.app',
    iosBundleId: 'com.example.orbitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEMgBKONZDD5f0gaWn_67ZRMPQkvhxLQI',
    appId: '1:177992848215:web:817d767aaabcba9daee412',
    messagingSenderId: '177992848215',
    projectId: 'orbit-app-85564',
    authDomain: 'orbit-app-85564.firebaseapp.com',
    storageBucket: 'orbit-app-85564.firebasestorage.app',
    measurementId: 'G-PVC81R0WGW',
  );
}
